# Generated by Django 5.1.3 on 2024-11-13 16:29

import medilabApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilabApp', '0003_appointment_doctor_alter_appointment_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[medilabApp.models.validate_no_empty])),
                ('email', models.EmailField(max_length=254, validators=[medilabApp.models.validate_no_empty])),
                ('subject', models.CharField(max_length=200, validators=[medilabApp.models.validate_no_empty])),
                ('message', models.TextField(validators=[medilabApp.models.validate_no_empty])),
            ],
        ),
    ]
