# Generated by Django 5.1.3 on 2024-11-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medilabApp', '0007_alter_user_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
