# Generated by Django 5.1.3 on 2024-11-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilabApp', '0008_rename_user_user1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
