# Generated by Django 5.1.3 on 2024-11-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilabApp', '0009_alter_user1_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user1',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
