# Generated by Django 5.1.3 on 2024-11-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilabApp', '0010_alter_user1_name_alter_user1_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='name',
            field=models.CharField(default=('USER1', 'user', '123'), max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user1',
            name='password',
            field=models.CharField(default='user', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user1',
            name='username',
            field=models.CharField(default='user1', max_length=150),
            preserve_default=False,
        ),
    ]
